HouseRentingSystem/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace HouseRentingSystem.Areas.Admin.Controllers
{
    public class HomeController : BaseController
    {       
        public IActionResult Index()
        {
            return View();
        }        
    }
}

HouseRentingSystem/Controllers/HomeController.cs
using HouseRentingSystem.Core.Contracts;
using HouseRentingSystem.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using static HouseRentingSystem.Areas.Admin.Constants.AdminConstant;

namespace HouseRentingSystem.Controllers
{
    public class HomeController : Controller
    {
        private readonly IHouseService houseService;

        public HomeController(IHouseService _houseService)
        {
            houseService = _houseService;
        }

        public async Task<IActionResult> Index()
        {
            if (User.IsInRole(AdminRoleName))
            {
                return RedirectToAction("Index", "Home", new { area = "Admin" });
            }
            var model = await houseService.LastThreeHousesAsync();

            return View(model);
        }
       
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HouseRentingSystem/Controllers/HousesController.cs
using HouseRentingSystem.Core.Contracts;
using HouseRentingSystem.Core.Extensions;
using HouseRentingSystem.Core.Models.Houses;
using HouseRentingSystem.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HouseRentingSystem.Controllers
{
	[Authorize]

	public class HousesController : Controller
	{
        private readonly IHouseService houseService;
        private readonly IAgentService agentService;

		public HousesController(
			IHouseService _houseService, 
			IAgentService _agentService)
		{
			houseService = _houseService;
			agentService = _agentService;
		}

        [AllowAnonymous]

		public async Task<IActionResult> All([FromQuery] AllHousesQueryModel query)
		{
			var resultQuery = await houseService.AllAsync(
				query.Category,
				query.SearchTerm,
				query.Sorting,
				query.CurrentPage,
				AllHousesQueryModel.HousesPerPage);

			query.TotalHousesCount = resultQuery.TotalHousesCount;
			query.Houses = resultQuery.Houses;

			query.Categories = await houseService.AllGategoriesNamesAsync();			

            return View(query);
		}

		public async Task<IActionResult> Mine()
		{
			IEnumerable<HouseServiceModel> myHouses;

			var userId = User.Id();

			if (await agentService.IsExistsByIdAsync(userId))
			{
				var currengAgentId = await agentService.GetAgentIdAsync(userId);

				myHouses = await houseService.AllHousesByAgentIdAsync(currengAgentId);
			}
			else
			{
				myHouses = await houseService.AllHousesByUserIdAsync(userId);
			}

            return View(myHouses);
        }

		public async Task<IActionResult> Details(int id, string information)
		{
			if (!await houseService.HouseExistsAsync(id))
			{
				return RedirectToAction(nameof(All));
			}			

			var model = await houseService.HouseDetailsByIdAsync(id);

            if (information != model.GetInformation())
            {
                return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
            }

            return View(model);
		}

		public async Task<IActionResult> Add()
		{
			if (!await agentService.IsExistsByIdAsync(this.User.Id()))
			{
				return RedirectToAction(nameof(AgentsController.Become), "Agent");
			}

			var model = new HouseFormModel()
			{
				Categories = await houseService.AllCategoriesAsync()
			};

			return View(model);
		}

		[HttpPost]

        public async Task<IActionResult> Add(HouseFormModel model)
        {
            if (!await agentService.IsExistsByIdAsync(this.User.Id()))
            {
                return RedirectToAction(nameof(AgentsController.Become), "Agent");
            }


            if (!await houseService.CategoryExists(model.CategoryId))
            {
                ModelState.AddModelError(nameof(model.CategoryId), "Category does not exist");
            }

            if (!ModelState.IsValid)
			{
				model.Categories = await houseService.AllCategoriesAsync();

                return View(model);
            }

			int agentId = await agentService.GetAgentIdAsync(this.User.Id());

			int id = await houseService.CreateAsync(model, agentId);

            return RedirectToAction(nameof(Details), new { id = id, information = model.GetInformation() });
        }

		public async Task<IActionResult> Edit(int id)
		{
			var model = new HouseFormModel();

			if (!await houseService.HouseExistsAsync(id))
			{
				return RedirectToAction(nameof(All));
			}

			if (!await houseService.HasAgentWithIdAsync(id, this.User.Id()))
			{
                return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
            }

			var house = await houseService.HouseDetailsByIdAsync(id);

			var houseCategoryId = await houseService.GetHouseCategoryIdAsync(house.Id);

			model.Title = house.Title;
			model.Description = house.Description;
			model.CategoryId = houseCategoryId;
			model.Categories = await houseService.AllCategoriesAsync();
			model.PricePerMonth = house.PricePerMonth;
			model.ImageUrl = house.ImageUrl;
			model.Address = house.Address;			

			return View(model);
		}

		[HttpPost]

		public async Task<IActionResult> Edit(HouseFormModel model, int id)
		{			
            if (!await houseService.HouseExistsAsync(id))
            {
				ModelState.AddModelError("", "House does not exist!");
                model.Categories = await houseService.AllCategoriesAsync();

                return View(model);
            }

            if (!await houseService.HasAgentWithIdAsync(id, this.User.Id()))
            {
                return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
            }

			if (!await houseService.CategoryExists(model.CategoryId))
			{
				ModelState.AddModelError(nameof(model.CategoryId), "Category does not exist!");
			}

			if (!ModelState.IsValid)
			{
				model.Categories = await houseService.AllCategoriesAsync();
				return View(model);
			}

			await houseService.EditHouseAsync(id, model);

            return RedirectToAction(nameof(Details), new { id = id, information = model.GetInformation() });
		}

		public async Task<IActionResult> Delete(int id)
		{
            if (!await houseService.HouseExistsAsync(id))
            {
                return RedirectToAction(nameof(All));
            }

            if (!await houseService.HasAgentWithIdAsync(id, this.User.Id()))
            {
                return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
            }

            var house = await houseService.HouseDetailsByIdAsync(id);

			var model = new HouseDeleteViewModel()
			{

				Title = house.Title,
				Address = house.Address,
				ImageUrl = house.ImageUrl
			};

			return View(model);
        }

        [HttpPost]

        public async Task<IActionResult> Delete(HouseDeleteViewModel model)
        {
            if (!await houseService.HouseExistsAsync(model.Id))
            {
                return RedirectToAction(nameof(All));
            }

            if (!await houseService.HasAgentWithIdAsync(model.Id, this.User.Id()))
            {
                return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
            }

			await houseService.DeleteAsync(model.Id);

			return RedirectToAction(nameof(All));
        }

        [HttpPost]

        public async Task<IActionResult> Rent(int id)
        {
            if (!await houseService.HouseExistsAsync(id))
            {
                return RedirectToAction(nameof(All));
            }

            if (await agentService.IsExistsByIdAsync(this.User.Id()))
            {
                //return BadRequest();
                return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
            }

			if (await houseService.IsRentedAsync(id))
			{
                return RedirectToAction(nameof(All));
            }

			await houseService.RentAsync(id, this.User.Id());

            return RedirectToAction(nameof(Mine));
        }

        [HttpPost]

        public async Task<IActionResult> Leave(int id)
        {
            if (!await houseService.HouseExistsAsync(id) || !await houseService.IsRentedAsync(id))
            {
                return RedirectToAction(nameof(All));
            }

			if (await houseService.IsRentedByUserWithIdAsync(id, this.User.Id()))
			{
                return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
            }

			await houseService.LeaveAsync(id);

            return RedirectToAction(nameof(Mine));
        }
    }
}

HouseRentingSystem/Views/Home/Index.cshtml
@model IEnumerable<HouseIndexServiceModel>

@{
    ViewData["Title"] = "Home Page";
    var houses = Model.ToList();
}

@if (!houses.Any())
{
    <div class="mt-4 p-5 bg-light">
        <h1 class="display-4">Welcome to the best place for renting houses!</h1>
        <p class="lead">
            There are no houses in the system currently available
            so why don't you just add one?
        </p>
        <hr class="my-4">
        <p class="lead">
            @if (this.User.Identity.IsAuthenticated)
            {
                <a asp-controller="Houses" asp-action="Add" class="btn btn-primary btn-lg"
                    role="button">Add House</a>
            }
        </p>
    </div>
}

<div class="mb-5"></div>

<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        @for (int i = 0; i < houses.Count(); i++)
        {
            var house = houses[i];
            <div class="carousel-item @(i == 0 ? "active" : string.Empty)">
                <img class="d-block w-100" style="height:500px"
                    src="@house.ImageUrl" alt="@house.Title">
                <div class="carousel-caption d-none d-md-block">
                    <h5>
                        <a class="btn btn-primary" asp-controller="Houses" asp-action="Details"
                            asp-route-id="@house.Id" 
                        asp-route-information="@house.GetInformation()"> @house.Title</a>
                    </h5>
                </div>
            </div>
        }
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

<div class="mb-5"></div>
<div class="row">
    <div class="col-12 text-center">
        <button class="btn btn-primary" id="statistics-button">Show Statistics</button>
    </div>
</div>

<div class="mt-4 p-5 bg-light d-none" id="statistics">
    <div class="row">
        <h2 class="col-md-6 text-center" id="total-houses"></h2>
        <h2 class="col-md-6 text-center" id="total-rents"></h2>
    </div>
</div>
@section Scripts {
    <script>
        $('#statistics-button').on('click', ev => {
            $.get('https://localhost:7083/api/statistics', (data) => {
                $('#total-houses').text(data.totalHouses + "Houses");
                $('#total-rents').text(data.totalRents + " Rents");
                $('#statistics').removeClass('d-none');
                $('#statistics-button').hide();
            });
        });
    </script>
}